[package]
name = "kanal"
version = "0.1.0-beta1"
edition = "2021"
authors = ["Khashayar Fereidani"]
description = "Fastest sync and async channel that Rust deserves"
repository = "https://github.com/fereidani/kanal"
keywords = ["channel", "mpsc", "mpmc", "csp", "async"]
categories = ["concurrency", "data-structures","asynchronous"]
license = "MIT"
readme = "README.md"

[dependencies]
lock_api = "0.4.7"

[dev-dependencies]
tokio = { version = "1", features =["rt-multi-thread", "test-util", "macros"] }
crossbeam = "0.8"

